import React, { useRef, useEffect } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  Animated,
  Share,
  ScrollView,
} from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { LinearGradient } from 'expo-linear-gradient';
import { GeneratedShloka } from '../../services/aiComposerService';

interface GeneratedShlokaCardProps {
  shloka: GeneratedShloka;
  onNewShloka: () => void;
}

export default function GeneratedShlokaCard({ shloka, onNewShloka }: GeneratedShlokaCardProps) {
  const fadeAnim = useRef(new Animated.Value(0)).current;
  const slideAnim = useRef(new Animated.Value(30)).current;
  const scaleAnim = useRef(new Animated.Value(0.95)).current;

  useEffect(() => {
    Animated.parallel([
      Animated.timing(fadeAnim, {
        toValue: 1,
        duration: 500,
        useNativeDriver: true,
      }),
      Animated.timing(slideAnim, {
        toValue: 0,
        duration: 500,
        useNativeDriver: true,
      }),
      Animated.spring(scaleAnim, {
        toValue: 1,
        tension: 50,
        friction: 8,
        useNativeDriver: true,
      }),
    ]).start();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleShare = async () => {
    try {
      await Share.share({
        message: `${shloka.sanskrit}\n\n${shloka.transliteration}\n\n${shloka.meaning}\n\n- Generated by ShlokaYug AI Composer`,
      });
    } catch (error) {
      console.log('Error sharing:', error);
    }
  };

  const handleCopy = () => {
    // In a real app, you'd use Clipboard API
    console.log('Copy shloka');
  };

  return (
    <Animated.View
      style={{
        opacity: fadeAnim,
        transform: [
          { translateY: slideAnim },
          { scale: scaleAnim },
        ],
      }}
    >
      {/* Success Header */}
      <View style={{ alignItems: 'center', marginBottom: 20 }}>
        <View
          style={{
            width: 64,
            height: 64,
            borderRadius: 32,
            backgroundColor: '#dcfce7',
            alignItems: 'center',
            justifyContent: 'center',
            marginBottom: 12,
          }}
        >
          <Ionicons name="checkmark-circle" size={36} color="#22c55e" />
        </View>
        <Text style={{ fontSize: 18, fontWeight: '700', color: '#1f2937' }}>
          Shloka Generated!
        </Text>
        <Text style={{ fontSize: 13, color: '#9ca3af', marginTop: 4 }}>
          Your custom Sanskrit verse is ready
        </Text>
      </View>

      {/* Main Shloka Card */}
      <View
        style={{
          backgroundColor: '#fffbf5',
          borderRadius: 20,
          overflow: 'hidden',
          borderWidth: 1,
          borderColor: '#fde68a',
          marginBottom: 16,
        }}
      >
        {/* Decorative top bar */}
        <LinearGradient
          colors={['#f97316', '#ea580c']}
          start={{ x: 0, y: 0 }}
          end={{ x: 1, y: 0 }}
          style={{ height: 4 }}
        />

        <View style={{ padding: 20 }}>
          {/* Sanskrit Text */}
          <View style={{ marginBottom: 16 }}>
            <Text
              style={{
                fontSize: 20,
                fontWeight: '600',
                color: '#92400e',
                lineHeight: 32,
                textAlign: 'center',
              }}
            >
              {shloka.sanskrit}
            </Text>
          </View>

          {/* Divider */}
          <View
            style={{
              height: 1,
              backgroundColor: '#fde68a',
              marginVertical: 16,
            }}
          />

          {/* Transliteration */}
          <View style={{ marginBottom: 16 }}>
            <Text
              style={{
                fontSize: 11,
                fontWeight: '600',
                color: '#9ca3af',
                letterSpacing: 1,
                textTransform: 'uppercase',
                marginBottom: 8,
              }}
            >
              Transliteration
            </Text>
            <Text
              style={{
                fontSize: 15,
                color: '#b45309',
                fontStyle: 'italic',
                lineHeight: 24,
                textAlign: 'center',
              }}
            >
              {shloka.transliteration}
            </Text>
          </View>

          {/* Meaning */}
          <View>
            <Text
              style={{
                fontSize: 11,
                fontWeight: '600',
                color: '#9ca3af',
                letterSpacing: 1,
                textTransform: 'uppercase',
                marginBottom: 8,
              }}
            >
              Meaning
            </Text>
            <Text
              style={{
                fontSize: 14,
                color: '#78716c',
                lineHeight: 22,
                textAlign: 'center',
              }}
            >
              {shloka.meaning}
            </Text>
          </View>
        </View>

        {/* Meta info */}
        <View
          style={{
            flexDirection: 'row',
            justifyContent: 'space-between',
            paddingHorizontal: 20,
            paddingVertical: 14,
            backgroundColor: '#fef7ee',
            borderTopWidth: 1,
            borderTopColor: '#fde68a',
          }}
        >
          <View style={{ flexDirection: 'row', alignItems: 'center' }}>
            <Ionicons name="musical-notes-outline" size={14} color="#b45309" />
            <Text style={{ fontSize: 12, color: '#b45309', marginLeft: 6, fontWeight: '500' }}>
              {shloka.meter} Meter
            </Text>
          </View>
          <View style={{ flexDirection: 'row', alignItems: 'center' }}>
            <Ionicons name="pricetag-outline" size={14} color="#b45309" />
            <Text style={{ fontSize: 12, color: '#b45309', marginLeft: 6, fontWeight: '500' }}>
              {shloka.theme}
            </Text>
          </View>
        </View>
      </View>

      {/* Word by Word Analysis */}
      {shloka.wordByWord && shloka.wordByWord.length > 0 && (
        <View
          style={{
            backgroundColor: '#ffffff',
            borderRadius: 16,
            padding: 16,
            marginBottom: 16,
            borderWidth: 1,
            borderColor: '#f3f4f6',
          }}
        >
          <Text
            style={{
              fontSize: 11,
              fontWeight: '600',
              color: '#9ca3af',
              letterSpacing: 1,
              textTransform: 'uppercase',
              marginBottom: 12,
            }}
          >
            Word-by-Word Meaning
          </Text>
          <ScrollView horizontal showsHorizontalScrollIndicator={false}>
            <View style={{ flexDirection: 'row', gap: 10 }}>
              {shloka.wordByWord.map((word, index) => (
                <View
                  key={index}
                  style={{
                    backgroundColor: '#fef7f0',
                    borderRadius: 12,
                    padding: 12,
                    minWidth: 100,
                    alignItems: 'center',
                  }}
                >
                  <Text style={{ fontSize: 16, fontWeight: '600', color: '#92400e' }}>
                    {word.sanskrit}
                  </Text>
                  <Text style={{ fontSize: 11, color: '#b45309', marginTop: 4, fontStyle: 'italic' }}>
                    {word.transliteration}
                  </Text>
                  <View
                    style={{
                      height: 1,
                      width: '100%',
                      backgroundColor: '#fde68a',
                      marginVertical: 8,
                    }}
                  />
                  <Text style={{ fontSize: 11, color: '#78716c', textAlign: 'center' }}>
                    {word.meaning}
                  </Text>
                </View>
              ))}
            </View>
          </ScrollView>
        </View>
      )}

      {/* Action Buttons */}
      <View style={{ flexDirection: 'row', gap: 10, marginBottom: 16 }}>
        <TouchableOpacity
          onPress={handleCopy}
          style={{
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: '#ffffff',
            borderRadius: 12,
            paddingVertical: 14,
            borderWidth: 1,
            borderColor: '#e5e7eb',
          }}
        >
          <Ionicons name="copy-outline" size={18} color="#6b7280" />
          <Text style={{ marginLeft: 8, color: '#6b7280', fontWeight: '600' }}>Copy</Text>
        </TouchableOpacity>

        <TouchableOpacity
          onPress={handleShare}
          style={{
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: '#ffffff',
            borderRadius: 12,
            paddingVertical: 14,
            borderWidth: 1,
            borderColor: '#e5e7eb',
          }}
        >
          <Ionicons name="share-outline" size={18} color="#6b7280" />
          <Text style={{ marginLeft: 8, color: '#6b7280', fontWeight: '600' }}>Share</Text>
        </TouchableOpacity>

        <TouchableOpacity
          style={{
            flex: 1,
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            backgroundColor: '#ffffff',
            borderRadius: 12,
            paddingVertical: 14,
            borderWidth: 1,
            borderColor: '#e5e7eb',
          }}
        >
          <Ionicons name="bookmark-outline" size={18} color="#6b7280" />
          <Text style={{ marginLeft: 8, color: '#6b7280', fontWeight: '600' }}>Save</Text>
        </TouchableOpacity>
      </View>

      {/* Generate New Button */}
      <TouchableOpacity
        onPress={onNewShloka}
        style={{
          flexDirection: 'row',
          alignItems: 'center',
          justifyContent: 'center',
          paddingVertical: 16,
        }}
      >
        <Ionicons name="refresh-outline" size={18} color="#f97316" />
        <Text style={{ marginLeft: 8, color: '#f97316', fontWeight: '600' }}>
          Generate Another Shloka
        </Text>
      </TouchableOpacity>
    </Animated.View>
  );
}
